#!/usr/bin/env python3
"""Разбор манифестов: какие ПРЯМЫЕ зависимости объявлены в файле.

Часть `check_new_dependency.py` (`cqg@1.83`) — гейт разрезан по планке 300 строк
(Delivery §9.1a п.5). Здесь только чтение форматов: по одной функции на экосистему
плюс выбор нужной по имени файла. Гейт (что считать новым и как об этом отчитаться)
остался во входном скрипте.

Лок-файлы сознательно не разбираются: они перечисляют ТРАНЗИТИВНЫЕ пакеты, и
решение «взяли новую зависимость» там утонет в шуме обновлений. Признак лока —
СОДЕРЖИМОЕ, а не имя: `pip-compile` пишет обычный `requirements.txt`.
"""

from __future__ import annotations

import json
import re

LOCKFILES = (
    "poetry.lock",
    "package-lock.json",
    "Cargo.lock",
    "yarn.lock",
    "pnpm-lock.yaml",
    "Gemfile.lock",
    "uv.lock",
)

#: Манифесты, которых разбор НЕ знает: XML (`pom.xml`, `*.csproj`) и DSL на языке
#: проекта (`build.gradle`, `mix.exs`) стоят дорого, `pubspec.yaml` требует YAML,
#: которого у контура нет. Список нужен не для чтения, а для честного молчания
#: (`coverage_note`): НЕНАЗВАННАЯ слепота дороже недостающего разбора.
UNREADABLE = ("pom.xml", "build.gradle", "build.gradle.kts", "mix.exs",
              "pubspec.yaml", "Podfile")
UNREADABLE_EXT = (".csproj", ".fsproj", ".vbproj")

#: Шапка генератора: `pip-compile` и `uv pip compile` кладут результат в файл с
#: именем `requirements.txt`, поэтому ПО ИМЕНИ лок неотличим от манифеста.
_LOCK_HEADER = re.compile(r"(?im)^#.*autogenerated by (pip-compile|uv)")


def is_lock_text(text: str) -> bool:
    """Лок ли это — ПО СОДЕРЖИМОМУ, а не по имени файла.

    `requirements.txt` от `pip-compile` перечисляет ТРАНЗИТИВНЫЕ пакеты, то есть
    подпадает ровно под запрет из шапки модуля, — но имя обещает манифест прямых
    зависимостей, и `extractor_for` отдавал его `names_requirements`. Цена:
    обновился `requests`, притянул `charset-normalizer` — гейт требует подписи
    человека за решение, которого никто не принимал, и его снимут (§4.3b).

    ⚠ ПОРЯДОК: сначала распознать, потом срезать. Признак живёт в КОММЕНТАРИЯХ
    (шапка и аннотации `# via <кто затянул>`), а `names_requirements` срезает их
    первой же строкой (`raw.split("#")[0]`) — то есть уничтожает улику до разбора.
    """
    if _LOCK_HEADER.search(text):
        return True
    # Одной аннотации мало: `# via` встречается и в рукописном комментарии.
    return len(re.findall(r"#\s+via\b", text)) >= 2


def _toml(text: str):
    """dict или None. None = нет tomllib (python<3.11) либо TOML не парсится."""
    try:
        import tomllib
    except ImportError:
        return None
    try:
        return tomllib.loads(text)
    except Exception:  # noqa: BLE001  # silent-ok: битый TOML — ниже фолбэк на regex
        return None


def _req_name(spec: str) -> str:
    """'requests[socks] >= 2.0 ; python_version<"3.9"' -> 'requests'."""
    head = spec.split(";")[0].strip()
    m = re.match(r"[A-Za-z0-9._-]+", head)
    return m.group(0).lower() if m else ""


def _toml_dep_names_fallback(text: str) -> set[str]:
    """Без tomllib: только участки, относящиеся к зависимостям.

    Сканировать весь файл нельзя: `name = "..."` в [project] попал бы в набор и
    добавление любого поля метаданных читалось бы как новая зависимость.
    """
    out: set[str] = set()
    in_dep_table = False
    in_dep_array = False
    for raw in text.splitlines():
        line = raw.split("#")[0].strip()
        if line.startswith("["):
            in_dep_table = "dependencies" in line
            in_dep_array = False
            continue
        if re.match(r"^(optional-)?dependencies\s*=", line):
            in_dep_array = "]" not in line
            for m in re.finditer(r'["\']([A-Za-z0-9._-]+)', line):
                out.add(m.group(1).lower())
            continue
        if in_dep_array:
            for m in re.finditer(r'["\']([A-Za-z0-9._-]+)', line):
                out.add(m.group(1).lower())
            if "]" in line:
                in_dep_array = False
            continue
        if in_dep_table:
            m = re.match(r"^([A-Za-z0-9._-]+)\s*=", line)
            if m:
                out.add(m.group(1).lower())
    return out




def _names_from_specs(specs) -> set[str]:
    """`["httpx>=0.27", …]` → `{"httpx", …}`. `None` и пустое — пустое множество."""
    return {_req_name(str(spec)) for spec in (specs or [])}


def _table_names(table) -> set[str]:
    """Имена КЛЮЧЕЙ таблицы зависимостей (форма poetry). `None` — пустое."""
    return {name.lower() for name in (table or {})}


def _pep621_names(data: dict) -> set[str]:
    """PEP 621: `[project]` + optional-dependencies + PEP 735 dependency-groups."""
    proj = data.get("project") or {}
    out = _names_from_specs(proj.get("dependencies"))
    for group in (proj.get("optional-dependencies") or {}).values():
        out |= _names_from_specs(group)
    for group in (data.get("dependency-groups") or {}).values():
        # PEP 735 разрешает в группе не только строки, но и `{include-group: …}`:
        # это ссылка на другую группу, а не зависимость, и имени в ней нет.
        out |= _names_from_specs(s for s in (group or []) if isinstance(s, str))
    return out


def _poetry_names(data: dict) -> set[str]:
    """`[tool.poetry]`: dependencies, dev-dependencies и именованные группы."""
    poetry = (data.get("tool") or {}).get("poetry") or {}
    out = _table_names(poetry.get("dependencies")) | _table_names(poetry.get("dev-dependencies"))
    for group in (poetry.get("group") or {}).values():
        out |= _table_names((group or {}).get("dependencies"))
    return out


def names_pyproject(text: str) -> set[str]:
    """Обе раскладки разом: PEP 621 и poetry живут в одном файле и обе законны.

    Разобрано на две функции (`cqg@1.83`): вместе это была самая ветвистая функция
    контура при двадцати двух строках — читать её приходилось целиком, чтобы
    понять, какая половина форматов сейчас важна.
    """
    data = _toml(text)
    if data is None:
        return _toml_dep_names_fallback(text)
    out = _pep621_names(data) | _poetry_names(data)
    out.discard("python")  # требование к рантайму, а не зависимость
    return {n for n in out if n}


def _cargo_section_names(table) -> set[str]:
    """Имена зависимостей из трёх секций ОДНОЙ таблицы Cargo.toml.

    Шов по сложности, а не по длине: те же три секции читаются и в корне
    манифеста, и в каждой `[target.*]`, и каждое чтение стоило ветвления —
    одиннадцать при пороге десять. Наружу выборка отдаёт одно множество имён.
    """
    return {n.lower()
            for key in ("dependencies", "dev-dependencies", "build-dependencies")
            for n in ((table or {}).get(key) or {})}


def names_cargo(text: str) -> set[str]:
    data = _toml(text)
    if data is None:
        return _toml_dep_names_fallback(text)
    out = _cargo_section_names(data)
    for target in (data.get("target") or {}).values():
        out |= _cargo_section_names(target)
    return out


def _json_sections(text: str, keys: tuple[str, ...]) -> set[str]:
    """Имена ключей перечисленных секций JSON-манифеста. Не объект — пусто."""
    try:
        data = json.loads(text)
    except ValueError:
        data = None
    if not isinstance(data, dict):
        return set()
    out: set[str] = set()
    for key in keys:
        section = data.get(key)
        if isinstance(section, dict):
            out.update(n.lower() for n in section)
    return out


def names_package_json(text: str) -> set[str]:
    return _json_sections(text, ("dependencies", "devDependencies",
                                 "peerDependencies", "optionalDependencies"))


def names_composer(text: str) -> set[str]:
    """PHP: `php` и `ext-*` — требования к рантайму, а не зависимости (тот же
    случай, что `python` в pyproject)."""
    return {n for n in _json_sections(text, ("require", "require-dev"))
            if n != "php" and not n.startswith("ext-")}


def names_gemfile(text: str) -> set[str]:
    """Ruby: имя — первый строковый аргумент `gem`. Закомментированная строка
    сюда не попадает: `^\\s*gem` с `#` в начале не совпадает."""
    return {m.group(1).lower() for m in
            re.finditer(r"""(?m)^\s*gem\s+['"]([A-Za-z0-9._-]+)['"]""", text)}


def names_requirements(text: str) -> set[str]:
    out: set[str] = set()
    for raw in text.splitlines():
        line = raw.split("#")[0].strip()
        if not line or line.startswith("-"):  # -r / -e / --index-url
            continue
        name = _req_name(line)
        if name:
            out.add(name)
    return out


def names_go_mod(text: str) -> set[str]:
    out: set[str] = set()
    block = False
    for raw in text.splitlines():
        line = raw.split("//")[0].strip()
        if line.startswith("require") and line.endswith("("):
            block = True
            continue
        if block:
            if line == ")":
                block = False
            elif line:
                out.add(line.split()[0].lower())
            continue
        if line.startswith("require "):
            rest = line[len("require ") :].split()
            if rest:
                out.add(rest[0].lower())
    return out


def names_swift(text: str) -> set[str]:
    out: set[str] = set()
    for m in re.finditer(
        r'\.package\s*\(\s*(?:name:\s*"([^"]+)"|url:\s*"([^"]+)")', text
    ):
        name = m.group(1) or (m.group(2) or "").rstrip("/").rsplit("/", 1)[-1]
        if name.endswith(".git"):
            name = name[:-4]
        if name:
            out.add(name.lower())
    return out


EXTRACTORS = (
    ("pyproject.toml", names_pyproject),
    ("Cargo.toml", names_cargo),
    ("package.json", names_package_json),
    # Ruby и PHP: разбор короток и надёжен, а стеки контур уже объявил своими
    # (`.rb`/`.php` есть и в `SOURCE_EXT` доктора, и в `TEST_TEXT_SUFFIXES`).
    # `Gemfile.lock` при этом с начала лежал в `LOCKFILES` — Ruby был известен
    # ровно с той стороны, где его надо НЕ читать.
    ("composer.json", names_composer),
    ("Gemfile", names_gemfile),
    ("go.mod", names_go_mod),
    ("Package.swift", names_swift),
)


def extractor_for(path: str):
    """Выбор разбора по ИМЕНИ — дёшево, зовётся на каждый путь из `git ls-files`.
    Содержимое (лок или манифест) судит `is_lock_text` у того, кто уже прочёл файл.
    """
    base = path.rsplit("/", 1)[-1]
    if base in LOCKFILES:
        return None
    for name, fn in EXTRACTORS:
        if base == name:
            return fn
    if base.startswith("requirements") and base.endswith(".txt"):
        return names_requirements
    return None


def unreadable_manifests(paths) -> list[str]:
    """Манифесты, которые гейт ВИДИТ в дереве, но читать не умеет (`UNREADABLE`)."""
    return sorted(p for p in paths
                  if p.rsplit("/", 1)[-1] in UNREADABLE or p.endswith(UNREADABLE_EXT))

